export interface IPhoto {
  id: number;
  alt: string;
}

export const photos: IPhoto[] = [
  { id: 1001, alt: '"Vesta goes brrrrr..." in een regenboogpatroon', },
  { id: 1002, alt: 'Drie gekleurde cirkels met stip', },
  { id: 1003, alt: 'Random kleurvolle stukken', },
  { id: 1004, alt: 'Link, uit de Zelda games', },
  { id: 1005, alt: 'Rode en groene Mario Bros paddo', },
  { id: 1006, alt: 'Super Mario\'s', },
  { id: 1007, alt: 'Vliegende Superman', },
  { id: 1008, alt: 'Hamburger en friet', },
  { id: 1009, alt: 'Bier en fris', },
  { id: 1010, alt: 'Vuurbloem uit Mario Bros', },
  { id: 1011, alt: 'Captain Comic en Commander Keen', },
  { id: 1012, alt: 'Drie gekleurde cirkels met stip', },
  { id: 1013, alt: 'Among Us poppetjes', },
  { id: 1014, alt: 'Star Trek Enterprise', },
  { id: 1015, alt: '"AOC"', },
  { id: 1016, alt: 'Super Mario Bros 1: wereld 1-1', },
  { id: 1017, alt: 'Sphinx-achtige kat', },
  { id: 1018, alt: 'Tetrisblokken', },
  { id: 1019, alt: 'Twee "Minions"', },
  { id: 1020, alt: 'Lakitu uit Super Mario Bros', },
  { id: 1021, alt: 'Super Mario World "?" en "!" blokken', },
  { id: 1022, alt: 'Regenboogpatroon (verticaal)', },
  { id: 1023, alt: 'Zonsondergang bij het water', },
  { id: 1024, alt: '"CON"', },
  { id: 1025, alt: 'INFI-CON Programma', },
  { id: 1026, alt: 'Fabriek met rookpluimen', },
  { id: 1027, alt: 'Mondriaan-esque beeld', },
  { id: 1028, alt: 'QWERTY keyboard layout', },
  { id: 1029, alt: '"UX!"', },
  { id: 1030, alt: 'Kameel', },
  { id: 1031, alt: 'Gekleurde geometrische vormen', },
  { id: 1032, alt: 'Sphinx-achtige kat met blauwe achtergrond', },
  { id: 1033, alt: '"ABC"', },
  { id: 1034, alt: 'Figuurtje uit Worms', },
  { id: 1035, alt: 'Driemaster', },
  { id: 1036, alt: 'Magische lamp', },
  { id: 1037, alt: 'Bord met vork en mes', },
  { id: 1038, alt: '"infi"', },
  { id: 1039, alt: 'Nooduitgang bordje', },
  { id: 1040, alt: 'Appel', },
  { id: 1041, alt: 'Regenboogpatroon (horizontaal)', },
  { id: 1042, alt: 'Atari logo in regenboogpatroon', },
  { id: 1043, alt: 'Groen monster', },
  { id: 1044, alt: 'Vuurspugend draakje', },
  { id: 1045, alt: 'Arkanoid', },
  { id: 1046, alt: 'Tie Fighter', },
  { id: 1047, alt: 'Dopefish', },
  { id: 1048, alt: 'Konijn met wortel', },
  { id: 1049, alt: '"INFI"', },
  { id: 1050, alt: 'Homer ♥ Marge', },
  { id: 1051, alt: 'Kale man naast een vrouw', },
  { id: 1052, alt: 'Zwemmend eendje', },
  { id: 1053, alt: 'Pacman die een geest achternajaagt', },
  { id: 1054, alt: 'Krab', },
  { id: 1055, alt: 'Schildpad die een tweede schildpad ziet', },
  { id: 1056, alt: 'Batman signaal', },
  { id: 1057, alt: '"Vesta goes brrrrr..." in een regenboogpatroon', },
  { id: 1058, alt: '"What did one plate say to the other? Dinner is on me!"', },
  { id: 1059, alt: '"Why did the clydesdale give the pony a glass of water? Because he was a little horse!"', },
  { id: 1060, alt: '"They\'re making a movie about clocks. It\'s about time.', },
  { id: 1061, alt: '"Why did the scarecrow win an award? Because he was outstanding in his field."', },
  { id: 1062, alt: '"What did the mountain climber name his son? Cliff."', },
  { id: 1063, alt: 'Regenwoklkjes met weervoorspelling Amsterdam', },
  { id: 1064, alt: '"I ♥ INFI"', },
  { id: 1065, alt: '"Marije Jansen is medewerker van de dag"', },
  { id: 1066, alt: '"What kind of music do planets listen to? Nep-tunes."', },
  { id: 1067, alt: 'Groene alien met handen in de lucht', },
  { id: 1068, alt: '"Jeroen was lolled by Jeroen"', },
  { id: 1069, alt: '"Jeroen was lolled by vestabot"', },
  { id: 1070, alt: '"A man tried to sell me a coffin today. I told him that\'s the last thing I need."', },
  { id: 1071, alt: '"Vesta goes brrrrr..." in een regenboogpatroon', },
  { id: 1072, alt: 'NES controller', },
  { id: 1073, alt: 'SNES controller', },
  { id: 1074, alt: '"Vesta goes brrrrr..." in een regenboogpatroon', },
  { id: 1075, alt: '"Vesta goes brrrrr..." in een regenboogpatroon', },
  { id: 1076, alt: 'Twee paaseieren en een paashaas', },
  { id: 1077, alt: 'Palmboom naast strand', },
  { id: 1078, alt: 'Equalizer bars', },
  { id: 1079, alt: 'Hond met bot', },
];
