export const photos = [
  { id: 1001, alt: '"Vesta goes brrrrr..." in a rainbow pattern', },
  { id: 1002, alt: 'Three colored circles with dots', },
  { id: 1003, alt: 'Random colorful areas', },
  { id: 1004, alt: 'Link from the Zelda games', },
  { id: 1005, alt: 'Large and 1UP mushrooms', },
  { id: 1006, alt: 'Super Mario\'s face', },
  { id: 1007, alt: 'Superman flying', },
  { id: 1008, alt: 'Hamburger and fries', },
  { id: 1009, alt: 'Beer and soda', },
  { id: 1010, alt: 'Fire Flower from Mario Bros', },
  { id: 1011, alt: 'Captain Comic and Commander Keen', },
  { id: 1012, alt: 'Three colored circles with dots', },
  { id: 1013, alt: 'Among Us figures', },
  { id: 1014, alt: 'Star Trek Enterprise', },
  { id: 1015, alt: '"AOC"', },
  { id: 1016, alt: 'Super Mario Bros 1 initial level', },
  { id: 1017, alt: 'Sphynx-like cat figure', },
  { id: 1018, alt: 'Tetris blocks configuration', },
  { id: 1019, alt: 'Two "Minions"', },
  { id: 1020, alt: 'Lakitu from Super Mario Bros', },
  { id: 1021, alt: 'Super Mario World "?" and "!" blocks', },
  { id: 1022, alt: 'Rainbow pattern, vertical', },
  { id: 1023, alt: 'Sunset over water', },
  { id: 1024, alt: '"CON"', },
  { id: 1025, alt: 'INFI-CON Programme', },
  { id: 1026, alt: 'Factory with clouds from its pipes', },
  { id: 1027, alt: 'Mondriaan-inspired blocks', },
  { id: 1028, alt: 'QWERTY keyboard layout', },
  { id: 1029, alt: '"UX!"', },
  { id: 1030, alt: 'Camel', },
  { id: 1031, alt: 'Colored geometric shapes', },
  { id: 1032, alt: 'Sphynx-like cat against blue background', },
  { id: 1033, alt: '"ABC"', },
  { id: 1034, alt: 'Worms-like figure', },
  { id: 1035, alt: 'Ship with three sails', },
  { id: 1036, alt: 'Magic lamp', },
  { id: 1037, alt: 'Plate, fork, knife', },
  { id: 1038, alt: '"infi"', },
  { id: 1039, alt: 'Exit sign', },
  { id: 1040, alt: 'Apple', },
  { id: 1041, alt: 'Rainbow pattern, horizontal', },
  { id: 1042, alt: 'Atari logo with rainbow pattern', },
  { id: 1043, alt: 'Green monster', },
  { id: 1044, alt: 'Crude dragon breathing fire', },
  { id: 1045, alt: 'Arkanoid', },
  { id: 1046, alt: 'Tie Fighter', },
  { id: 1047, alt: 'Dopefish', },
  { id: 1048, alt: 'Rabbit with carrot', },
  { id: 1049, alt: '"INFI"', },
  { id: 1050, alt: 'Homer ♥ Marge', },
  { id: 1051, alt: 'Bald man and woman', },
  { id: 1052, alt: 'Swimming duckling', },
  { id: 1053, alt: 'Pacman chasing a ghost', },
  { id: 1054, alt: 'Crab', },
  { id: 1055, alt: 'Turtle facing a second turtle', },
  { id: 1056, alt: 'Batman signal', },
  { id: 1057, alt: '"Vesta goes brr" inside rainbow pattern', },
  { id: 1058, alt: '"What did one plate say to the other? Dinner is on me!"', },
  { id: 1059, alt: '"Why did the clydesdale give the pony a glass of water? Because he was a little horse!"', },
  { id: 1060, alt: '"They\'re making a movie about clocks. It\'s about time.', },
  { id: 1061, alt: '"Why did the scarecrow win an award? Because he was outstanding in his field."', },
  { id: 1062, alt: '"What did the mountain climber name his son? Cliff."', },
  { id: 1063, alt: 'Clouds and weather forecast for Amsterdam', },
  { id: 1064, alt: '"I ♥ INFI"', },
  { id: 1065, alt: '"Marije Jansen is medewerker van de dag"', },
  { id: 1066, alt: '"What kind of music do planets listen to? Nep-tunes."', },
  { id: 1067, alt: 'Green alien with hands in the air', },
  { id: 1068, alt: '"Jeroen was lolled by Jeroen"', },
  { id: 1069, alt: '"Jeroen was lolled by vestabot"', },
  { id: 1070, alt: '"A man tried to sell me a coffin today. I told him that\'s the last thing I need."', },
  { id: 1071, alt: '"Vesta goes brrrrr..." in a rainbow pattern', },
  { id: 1072, alt: 'NES controller', },
  { id: 1073, alt: 'SNES controller', },
  { id: 1074, alt: '"Vesta goes brrrrr..." in a rainbow pattern', },
  { id: 1075, alt: '"Vesta goes brrrrr..." in a rainbow pattern', },
];
